services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres_service"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: option123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
